#!/bin/sh
# Regenerates probes/nvk/snake3d_font.h from the 5x7 glyphs of draw/src/font.rs.
cd "$(dirname "$0")" && python3 - <<'PY'
import re
src = open('../../draw/src/font.rs').read()
body = src[src.index('fn glyph_5x7'):]
body = body[:body.index('_ => [0; 7]')]
out = ["/* The 5x7 pixel font of draw/src/font.rs (rows top to bottom, leftmost column in bit 4), generated by probes/nvk/gen-font.sh: do not edit. */",
       "static const struct { char ch; unsigned char rows[7]; } snake_font[] = {"]
for m in re.finditer(r"b'(.)' => \[([^\]]*)\]", body):
    out.append("   { '%s', { %s } }," % (m.group(1), m.group(2)))
out.append("};")
open('snake3d_font.h', 'w').write("\n".join(out) + "\n")
PY
