#!/usr/bin/env python3
"""Regenerate userspace/c/nvgpu_shaders.h from the SASS fixtures of the nvgpu crate.

    python3 scripts/gen-nvgpu-shader-header.py

The fixtures (`nvgpu/fixtures/shader-*-sm86.bin`) are what `nvgpu/gen/shader/extract.py` cuts out of `nvcc -arch=sm_86` cubins; a
host test (`nvgpu::qmd::tests::the_c_test_carries_the_kernels_shaders`) fails when this header is stale.
"""
import pathlib

root = pathlib.Path(__file__).resolve().parent.parent
shaders = [("fill", "shader-fill-sm86.bin"), ("copy", "shader-copy-sm86.bin"), ("fillwt", "shader-fillwt-sm86.bin")]
out = ["// Generated by scripts/gen-nvgpu-shader-header.py from nvgpu/fixtures/shader-*-sm86.bin: do not edit.",
       "// SASS for SM86 (`nvcc -arch=sm_86`, sources in nvgpu/gen/shader/*.cu), 8 registers each, kernel parameters from c[0x0][0x160].",
       "#pragma once", "#include <stdint.h>", ""]
for name, f in shaders:
    b = (root / "nvgpu/fixtures" / f).read_bytes()
    out.append(f"static const uint8_t nvg_shader_{name}[{len(b)}] = {{")
    for i in range(0, len(b), 16):
        out.append("   " + ", ".join(f"0x{x:02x}" for x in b[i:i + 16]) + ",")
    out.append("};")
    out.append("")
(root / "userspace/c/nvgpu_shaders.h").write_text("\n".join(out))
