#!/usr/bin/env bash
# scripts/write-cmatrix-config.sh <output-path>
#
# Writes the config.h a normal `./configure` run over cmatrix/configure.ac
# would generate — build glue, same category as build-busybox.sh's
# cc-wrapper.sh or build-libtinfo.sh's own cc wrapper, not part of the
# ported program. cmatrix.c itself is untouched upstream source.
#
# What's deliberately left undefined (cmatrix.c falls back to its own
# `#else`/`#ifndef` branches for all of these, so omitting a define is a
# real, tested code path upstream already has — not a guess):
#   HAVE_CONSOLECHARS / HAVE_SETFONT — Linux virtual-console font
#     switching (`consolechars`/`setfont` external tools) for the
#     alternate charset. This kernel's console is our own framebuffer
#     text renderer, not a Linux vt — there is no font to switch.
#   HAVE_RESIZETERM / HAVE_WRESIZE — dynamic terminal resize. This
#     kernel's framebuffer console has a fixed size for the life of a
#     process; SIGWINCH is never raised, so the resize path in cmatrix.c
#     (guarded by these) never runs regardless.
#   USE_TIOCSTI — Cygwin-only path that stuffs synthetic input via
#     ioctl(TIOCSTI, ...); this kernel's ioctl doesn't implement it, and
#     it's dead on every real Linux target too, not just this one.
#   HAVE_USE_DEFAULT_COLORS — leaves cmatrix on its own portable
#     COLOR_BLACK fallback instead of use_default_colors() (present in
#     our libncursesw.a, but the fallback is simpler and just as correct
#     for this console, which always paints an explicit background).
#
# What IS defined: exactly the standard headers this port's sysroot
# actually provides (see mlibc-port/constanos-sysdeps and sysroot/usr/
# include after scripts/setup-mlibc.sh) — unistd.h, sys/ioctl.h,
# termios.h, getopt.h (getopt_long included, verified present).

set -euo pipefail

if [ $# -ne 1 ]; then
    echo "usage: $0 <output-path>" >&2
    exit 1
fi

OUT="$1"
mkdir -p "$(dirname "$OUT")"

cat > "$OUT" <<'EOF'
/* Generated by scripts/write-cmatrix-config.sh — see that script for why
 * each define is (or is deliberately not) present. Not upstream source. */
#ifndef CMATRIX_CONFIG_H
#define CMATRIX_CONFIG_H

#define HAVE_UNISTD_H 1
#define HAVE_SYS_IOCTL_H 1
#define HAVE_TERMIOS_H 1
#define HAVE_GETOPT_H 1
/* Matches cmatrix/configure.ac's AC_INIT([cmatrix], [2.0], ...) */
#define VERSION "2.0"

#endif /* CMATRIX_CONFIG_H */
EOF

echo "write-cmatrix-config: $OUT ready"
