//! Display modes (phase 5.7): the ones the EDID lists, CVT reduced
//! blanking v2 for the rest, and the core-channel methods that put one on a
//! head.
//!
//! - [`Mode`] is DRM's `drm_display_mode` reduced to what the head needs:
//!   the four horizontal and vertical positions (`hdisplay`,
//!   `hsync_start`, `hsync_end`, `htotal`, same for v), the pixel clock
//!   and the sync polarities. Interlaced modes are not taken.
//! - [`Mode::from_timing`] — an EDID detailed timing, as DRM's
//!   `drm_mode_detailed` (`drm_edid.c`) builds it.
//! - [`cvt_rb2`] — VESA CVT 1.2 reduced blanking v2, steps 8-11 of Linux's
//!   `drm_cvt_mode` (`drm_modes.c:780-799`, which only has v1) with v2's
//!   constants. Tested against `edid-decode 1.32.0 --cvt w=,h=,fps=,rb=2`.
//! - [`Mode::methods`] — `nv50_head_atomic_check_mode` (`dispnv50/head.c:283-330`)
//!   then `headc57d_mode` + `headc57d_or` (`dispnv50/headc57d.c:43-76,
//!   201-245`): the values nouveau pushes for a mode; tested against the
//!   round-2 push of `trace-nogsp-vrampush` (`fixtures/modeset-push.txt`).
//! - [`select`] — which mode a request (`WxH@Hz`) means, and the limits a
//!   generated one must meet (the EDID's range descriptor).

use alloc::vec::Vec;

use crate::edid::{Edid, Range, Timing};
use crate::vblank::HeadTiming;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Source {
    /// The EDID's detailed timing number `n` (0 = the preferred one).
    Edid(u8),
    /// Generated by [`cvt_rb2`].
    Cvt,
    /// Read back from a head the firmware lit.
    Gop,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Mode {
    pub hdisplay: u16,
    pub hsync_start: u16,
    pub hsync_end: u16,
    pub htotal: u16,
    pub vdisplay: u16,
    pub vsync_start: u16,
    pub vsync_end: u16,
    pub vtotal: u16,
    pub clock_khz: u32,
    /// `DRM_MODE_FLAG_NHSYNC` / `NVSYNC`.
    pub nhsync: bool,
    pub nvsync: bool,
    pub source: Source,
}

impl Mode {
    /// `drm_mode_detailed` for a progressive DTD: sync start = active +
    /// offset, end = start + width, total = active + blank. `None` for an
    /// interlaced one or a sync pulse past the blanking (DRM clamps those;
    /// neither monitor here has one).
    pub fn from_timing(t: &Timing, n: u8) -> Option<Mode> {
        if t.interlaced || t.pixclk_khz == 0 {
            return None;
        }
        let m = Mode {
            hdisplay: t.hactive,
            hsync_start: t.hactive + t.hsync_offset,
            hsync_end: t.hactive + t.hsync_offset + t.hsync_width,
            htotal: t.hactive + t.hblank,
            vdisplay: t.vactive,
            vsync_start: t.vactive + t.vsync_offset,
            vsync_end: t.vactive + t.vsync_offset + t.vsync_width,
            vtotal: t.vactive + t.vblank,
            clock_khz: t.pixclk_khz,
            nhsync: !t.hsync_positive,
            nvsync: !t.vsync_positive,
            source: Source::Edid(n),
        };
        m.sane().then_some(m)
    }

    /// Every position in order and inside the total.
    fn sane(&self) -> bool {
        self.hdisplay > 0
            && self.hdisplay < self.hsync_start
            && self.hsync_start < self.hsync_end
            && self.hsync_end <= self.htotal
            && self.vdisplay > 0
            && self.vdisplay < self.vsync_start
            && self.vsync_start < self.vsync_end
            && self.vsync_end <= self.vtotal
    }

    pub fn size(&self) -> (u16, u16) {
        (self.hdisplay, self.vdisplay)
    }

    /// Refresh in mHz.
    pub fn refresh_mhz(&self) -> u64 {
        let den = self.htotal as u64 * self.vtotal as u64;
        if den == 0 {
            return 0;
        }
        (self.clock_khz as u64 * 1_000_000 + den / 2) / den
    }

    /// `drm_mode_vrefresh`: rounded to whole hertz.
    pub fn refresh_hz(&self) -> u32 {
        ((self.refresh_mhz() + 500) / 1000) as u32
    }

    /// Line rate in kHz, rounded.
    pub fn hfreq_khz(&self) -> u32 {
        (self.clock_khz + self.htotal as u32 / 2) / self.htotal.max(1) as u32
    }

    /// The raster in the head's terms: `nv50_head_atomic_check_mode`
    /// (`head.c:298-306`): the hardware's line starts one unit into the
    /// sync pulse.
    pub fn raster(&self) -> Raster {
        let h_synce = self.hsync_end - self.hsync_start - 1;
        let h_blanke = self.htotal - self.hsync_start - 1;
        let v_synce = self.vsync_end - self.vsync_start - 1;
        let v_blanke = self.vtotal - self.vsync_start - 1;
        Raster {
            h_active: self.htotal,
            h_synce,
            h_blanke,
            h_blanks: h_blanke + self.hdisplay,
            v_active: self.vtotal,
            v_synce,
            v_blanke,
            v_blanks: v_blanke + self.vdisplay,
        }
    }

    /// What the head's ARM state reads once this mode is latched
    /// (`vblank::HeadTiming`'s fields are the same registers), at the
    /// output depth `depth_code`.
    pub fn timing(&self, depth_code: u8) -> HeadTiming {
        let r = self.raster();
        HeadTiming {
            htotal: r.h_active,
            vtotal: r.v_active,
            hsynce: r.h_synce,
            vsynce: r.v_synce,
            hblanke: r.h_blanke,
            vblanke: r.v_blanke,
            hblanks: r.h_blanks,
            vblanks: r.v_blanks,
            hz: self.clock_khz * 1000,
            depth_code,
        }
    }

    /// The inverse of [`Mode::timing`]: the mode a head scans out, from
    /// its state and its `HEAD_SET_CONTROL_OUTPUT_RESOURCE` (polarities).
    /// Used for what the GOP left.
    pub fn from_head(t: &HeadTiming, or: u32) -> Mode {
        // blanke = total - sync_start - 1, synce = sync_end - sync_start - 1,
        // blanks = blanke + display (`head.c:298-306`).
        let hss = t.htotal.wrapping_sub(t.hblanke).wrapping_sub(1);
        let vss = t.vtotal.wrapping_sub(t.vblanke).wrapping_sub(1);
        Mode {
            hdisplay: t.hblanks.wrapping_sub(t.hblanke),
            hsync_start: hss,
            hsync_end: hss.wrapping_add(t.hsynce).wrapping_add(1),
            htotal: t.htotal,
            vdisplay: t.vblanks.wrapping_sub(t.vblanke),
            vsync_start: vss,
            vsync_end: vss.wrapping_add(t.vsynce).wrapping_add(1),
            vtotal: t.vtotal,
            clock_khz: t.hz / 1000,
            nhsync: or & OR_HSYNC_NEGATIVE != 0,
            nvsync: or & OR_VSYNC_NEGATIVE != 0,
            source: Source::Gop,
        }
    }

    /// The core-channel methods that set this mode on `head`, in
    /// `headc57d_mode`'s order, then `headc57d_or`'s. `or_armed` is the
    /// head's current `HEAD_SET_CONTROL_OUTPUT_RESOURCE`: its depth, CRC
    /// mode and packet window are kept, only the polarities change (nouveau
    /// rebuilds the same word from its state, `headc57d.c:68-74`).
    /// `HEAD_SET_HEAD_USAGE_BOUNDS` is not pushed: the GOP's value stays.
    pub fn methods(&self, head: u32, or_armed: u32) -> [(u32, u32); 9] {
        let r = self.raster();
        let hd = head * HEAD_STRIDE;
        let xy = |x: u16, y: u16| (y as u32) << 16 | x as u32;
        let hz = self.clock_khz * 1000;
        let or = (or_armed & !(OR_HSYNC_NEGATIVE | OR_VSYNC_NEGATIVE))
            | if self.nhsync { OR_HSYNC_NEGATIVE } else { 0 }
            | if self.nvsync { OR_VSYNC_NEGATIVE } else { 0 };
        [
            (HEAD_SET_RASTER_SIZE + hd, xy(r.h_active, r.v_active)),
            (HEAD_SET_RASTER_SYNC_END + hd, xy(r.h_synce, r.v_synce)),
            (HEAD_SET_RASTER_BLANK_END + hd, xy(r.h_blanke, r.v_blanke)),
            (HEAD_SET_RASTER_BLANK_START + hd, xy(r.h_blanks, r.v_blanks)),
            // Progressive: blank2e = 0, blank2s = 1 (`head.c:320-321`).
            (HEAD_SET_RASTER_VERT_BLANK2 + hd, 1),
            (HEAD_SET_CONTROL + hd, 0),
            (HEAD_SET_PIXEL_CLOCK_FREQUENCY + hd, hz),
            (HEAD_SET_PIXEL_CLOCK_FREQUENCY_MAX + hd, hz),
            (HEAD_SET_CONTROL_OUTPUT_RESOURCE + hd, or),
        ]
    }
}

/// `struct nv50_head_mode` (`dispnv50/atom.h`), progressive only.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Raster {
    pub h_active: u16,
    pub h_synce: u16,
    pub h_blanke: u16,
    pub h_blanks: u16,
    pub v_active: u16,
    pub v_synce: u16,
    pub v_blanke: u16,
    pub v_blanks: u16,
}

/// Core-channel head methods (`clc67d.h`), `+ head * 0x400`.
const HEAD_STRIDE: u32 = 0x400;
/// `clc67d.h:504`; HSYNC_POLARITY bit 2, VSYNC_POLARITY bit 3
/// (`clc67d.h:509,512`), 1 = negative.
pub const HEAD_SET_CONTROL_OUTPUT_RESOURCE: u32 = 0x2004;
const OR_HSYNC_NEGATIVE: u32 = 1 << 2;
const OR_VSYNC_NEGATIVE: u32 = 1 << 3;
/// `clc67d.h:565` (nouveau writes it by number, `headc57d.c:230`: interlace).
pub const HEAD_SET_CONTROL: u32 = 0x2008;
/// `clc67d.h:691,737`.
pub const HEAD_SET_PIXEL_CLOCK_FREQUENCY: u32 = 0x200c;
pub const HEAD_SET_PIXEL_CLOCK_FREQUENCY_MAX: u32 = 0x2028;
/// `clc67d.h:826,829,832,835`.
pub const HEAD_SET_RASTER_SIZE: u32 = 0x2064;
pub const HEAD_SET_RASTER_SYNC_END: u32 = 0x2068;
pub const HEAD_SET_RASTER_BLANK_END: u32 = 0x206c;
pub const HEAD_SET_RASTER_BLANK_START: u32 = 0x2070;
/// Not in the header; `headc57d.c:229` writes it by number.
pub const HEAD_SET_RASTER_VERT_BLANK2: u32 = 0x2074;

// CVT 1.2 reduced blanking v2 (VESA CVT v1.2 table 3-2; the values
// edid-decode 1.32.0's `calc_cvt_mode` uses for `rb=2`).
/// Minimum vertical blanking, µs (the same 460 as v1, `drm_modes.c:773`).
const RB_MIN_V_BLANK_US: u64 = 460;
const RB2_H_BLANK: u16 = 80;
const RB2_H_SYNC: u16 = 32;
const RB2_H_FPORCH: u16 = 8;
const RB2_V_SYNC: u16 = 8;
const RB2_V_BPORCH: u16 = 6;
const RB2_MIN_V_FPORCH: u16 = 1;

/// CVT-RB2 for `w`x`h` at `hz` (progressive, no margins, no 1000/1001
/// multiplier). Steps 8-11 of `drm_cvt_mode`'s reduced-blanking branch
/// with exact integer arithmetic: vblank lines = floor(460 µs / line
/// period) + 1, at least front porch + sync + back porch; pixel clock =
/// `hz * vtotal * htotal` floored to 1 kHz (v2's clock step). Sync:
/// +H, -V (`drm_modes.c:816-818`, same for v2).
///
/// edid-decode computes in floating point and floors the clock in MHz, so
/// for an exact multiple of 1 kHz it can land 1 kHz lower (1080p50:
/// 110.599 MHz there, 110.600 here).
pub fn cvt_rb2(w: u16, h: u16, hz: u32) -> Option<Mode> {
    if w == 0 || h == 0 || hz == 0 || RB_MIN_V_BLANK_US * hz as u64 >= 1_000_000 {
        return None;
    }
    let vbi = (RB_MIN_V_BLANK_US * h as u64 * hz as u64 / (1_000_000 - RB_MIN_V_BLANK_US * hz as u64)) as u16 + 1;
    let vblank = vbi.max(RB2_MIN_V_FPORCH + RB2_V_SYNC + RB2_V_BPORCH);
    let vtotal = h.checked_add(vblank)?;
    let htotal = w.checked_add(RB2_H_BLANK)?;
    let clock_khz = (hz as u64 * vtotal as u64 * htotal as u64 / 1000) as u32;
    let m = Mode {
        hdisplay: w,
        hsync_start: w + RB2_H_FPORCH,
        hsync_end: w + RB2_H_FPORCH + RB2_H_SYNC,
        htotal,
        vdisplay: h,
        vsync_start: vtotal - RB2_V_BPORCH - RB2_V_SYNC,
        vsync_end: vtotal - RB2_V_BPORCH,
        vtotal,
        clock_khz,
        nhsync: false,
        nvsync: true,
        source: Source::Cvt,
    };
    m.sane().then_some(m)
}

/// The EDID's progressive detailed timings, as modes, in EDID order.
pub fn edid_modes(e: &Edid) -> Vec<Mode> {
    e.timings.iter().enumerate().filter_map(|(i, t)| Mode::from_timing(t, i as u8)).collect()
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ModeError {
    /// `WxH@Hz` did not parse.
    Syntax,
    /// No EDID mode matches, and a generated one is out of the EDID's
    /// range (or there is no range descriptor to check it against).
    OutOfRange,
}

/// A request: `WxH@Hz`, e.g. `1920x1080@180`.
pub fn parse_request(s: &str) -> Result<(u16, u16, u32), ModeError> {
    let (size, hz) = s.split_once('@').ok_or(ModeError::Syntax)?;
    let (w, h) = size.split_once('x').ok_or(ModeError::Syntax)?;
    let n = |t: &str| t.trim().parse::<u32>().map_err(|_| ModeError::Syntax);
    let (w, h, hz) = (n(w)?, n(h)?, n(hz)?);
    if w == 0 || h == 0 || hz == 0 || w > 0x7fff || h > 0x7fff {
        return Err(ModeError::Syntax);
    }
    Ok((w as u16, h as u16, hz))
}

/// The mode `WxH@Hz` means for a monitor: the first EDID detailed timing
/// of that size whose refresh rounds to `hz` (as DRM names modes), else
/// CVT-RB2 if the EDID's range descriptor allows its vertical rate and
/// pixel clock. The range's horizontal limits are not applied: the ASUS
/// VG279Q3A's say 250-250 kHz, which its own detailed timings (67-202 kHz)
/// violate.
pub fn select(e: &Edid, w: u16, h: u16, hz: u32) -> Result<Mode, ModeError> {
    if let Some(m) = edid_modes(e).into_iter().find(|m| m.size() == (w, h) && m.refresh_hz() == hz) {
        return Ok(m);
    }
    let m = cvt_rb2(w, h, hz).ok_or(ModeError::OutOfRange)?;
    let r = e.range.ok_or(ModeError::OutOfRange)?;
    in_range(&m, &r).then_some(m).ok_or(ModeError::OutOfRange)
}

/// Vertical rate and pixel clock inside the range descriptor.
pub fn in_range(m: &Mode, r: &Range) -> bool {
    let hz = m.refresh_mhz();
    let clock_ok = r.max_pixclk_mhz == 0 || m.clock_khz <= r.max_pixclk_mhz as u32 * 1000;
    hz >= r.min_vfreq as u64 * 1000 && hz <= r.max_vfreq as u64 * 1000 && clock_ok
}

#[cfg(test)]
mod tests {
    use super::*;
    use alloc::format;
    use alloc::string::String;

    const ASUS: &[u8] = include_bytes!("../fixtures/edid-asus-vg279q3a.bin");
    const HP: &[u8] = include_bytes!("../fixtures/edid-hp-2309.bin");
    const PUSH: &str = include_str!("../fixtures/modeset-push.txt");

    fn asus() -> Edid {
        Edid::parse(ASUS).unwrap()
    }

    /// `edid-decode`'s "Hfront Hsync Hback Hpol / Vfront Vsync Vback Vpol"
    /// plus the clock in kHz.
    fn porches(m: &Mode) -> String {
        format!(
            "{}x{} {} kHz Hfront {} Hsync {} Hback {} Hpol {} Vfront {} Vsync {} Vback {} Vpol {}",
            m.hdisplay,
            m.vdisplay,
            m.clock_khz,
            m.hsync_start - m.hdisplay,
            m.hsync_end - m.hsync_start,
            m.htotal - m.hsync_end,
            if m.nhsync { 'N' } else { 'P' },
            m.vsync_start - m.vdisplay,
            m.vsync_end - m.vsync_start,
            m.vtotal - m.vsync_end,
            if m.nvsync { 'N' } else { 'P' },
        )
    }

    /// `edid-decode --cvt w=W,h=H,fps=F,rb=2` (1.32.0), transcribed.
    #[test]
    fn cvt_rb2_matches_edid_decode() {
        let cases: &[(u16, u16, u32, &str)] = &[
            (1920, 1080, 60, "1920x1080 133320 kHz Hfront 8 Hsync 32 Hback 40 Hpol P Vfront 17 Vsync 8 Vback 6 Vpol N"),
            (1920, 1080, 120, "1920x1080 274560 kHz Hfront 8 Hsync 32 Hback 40 Hpol P Vfront 50 Vsync 8 Vback 6 Vpol N"),
            (1920, 1080, 144, "1920x1080 333216 kHz Hfront 8 Hsync 32 Hback 40 Hpol P Vfront 63 Vsync 8 Vback 6 Vpol N"),
            (1920, 1080, 165, "1920x1080 385770 kHz Hfront 8 Hsync 32 Hback 40 Hpol P Vfront 75 Vsync 8 Vback 6 Vpol N"),
            (1920, 1080, 180, "1920x1080 424080 kHz Hfront 8 Hsync 32 Hback 40 Hpol P Vfront 84 Vsync 8 Vback 6 Vpol N"),
            (1920, 1080, 48, "1920x1080 106080 kHz Hfront 8 Hsync 32 Hback 40 Hpol P Vfront 11 Vsync 8 Vback 6 Vpol N"),
            // edid-decode: 110.599 MHz (its float floor; see `cvt_rb2`).
            (1920, 1080, 50, "1920x1080 110600 kHz Hfront 8 Hsync 32 Hback 40 Hpol P Vfront 12 Vsync 8 Vback 6 Vpol N"),
            (2560, 1440, 144, "2560x1440 586586 kHz Hfront 8 Hsync 32 Hback 40 Hpol P Vfront 89 Vsync 8 Vback 6 Vpol N"),
            (1280, 720, 60, "1280x720 60465 kHz Hfront 8 Hsync 32 Hback 40 Hpol P Vfront 7 Vsync 8 Vback 6 Vpol N"),
        ];
        for &(w, h, hz, want) in cases {
            let m = cvt_rb2(w, h, hz).unwrap();
            assert_eq!(porches(&m), want, "{}x{}@{}", w, h, hz);
            assert_eq!(m.source, Source::Cvt);
        }
        assert_eq!(cvt_rb2(1920, 1080, 180).unwrap().refresh_mhz(), 180_000);
        // 1280x720@60 floors its clock: edid-decode says 59.999405 Hz.
        assert_eq!(cvt_rb2(1280, 720, 60).unwrap().refresh_mhz(), 59_999);
        assert_eq!(cvt_rb2(1920, 1080, 0), None);
        assert_eq!(cvt_rb2(1920, 1080, 2174), None, "460 us of blanking leaves no active time");
    }

    /// The ASUS's four DTDs as `edid-decode` prints them
    /// (`fixtures/edid-asus-vg279q3a.txt`).
    #[test]
    fn edid_modes_match_edid_decode() {
        let got: Vec<String> = edid_modes(&asus()).iter().map(|m| format!("{} {}", porches(m), m.refresh_mhz())).collect();
        assert_eq!(
            got,
            [
                "1920x1080 148500 kHz Hfront 88 Hsync 44 Hback 148 Hpol P Vfront 4 Vsync 5 Vback 36 Vpol P 60000",
                "1920x1080 346500 kHz Hfront 48 Hsync 32 Hback 80 Hpol P Vfront 3 Vsync 5 Vback 69 Vpol N 143981",
                "1920x1080 401000 kHz Hfront 48 Hsync 32 Hback 80 Hpol P Vfront 3 Vsync 5 Vback 81 Vpol N 164917",
                "1920x1080 420780 kHz Hfront 48 Hsync 32 Hback 80 Hpol P Vfront 2 Vsync 8 Vback 35 Vpol N 179821",
            ]
        );
        // The HP's five: the two interlaced ones (DTD 4, 5) are dropped.
        let hp: Vec<String> = edid_modes(&Edid::parse(HP).unwrap()).iter().map(|m| format!("{:?} {}", m.source, porches(m))).collect();
        assert_eq!(
            hp,
            [
                "Edid(0) 1920x1080 148500 kHz Hfront 88 Hsync 44 Hback 148 Hpol P Vfront 4 Vsync 5 Vback 36 Vpol P",
                "Edid(1) 720x480 27000 kHz Hfront 16 Hsync 62 Hback 60 Hpol N Vfront 9 Vsync 6 Vback 30 Vpol N",
                "Edid(2) 720x576 27000 kHz Hfront 12 Hsync 64 Hback 68 Hpol N Vfront 5 Vsync 5 Vback 39 Vpol N",
            ]
        );
    }

    /// The round-2 core push of `trace-nogsp-vrampush` set head 0 to the
    /// ASUS's preferred mode: the same values, in `headc57d_mode`'s order.
    #[test]
    fn methods_replay_the_round2_push_for_head0() {
        let want = |mthd: u32| -> u32 {
            let line = PUSH
                .lines()
                .find(|l| l.contains("11.918881 core") && l.split_whitespace().nth(2) == Some(&format!("{:04x}", mthd)))
                .unwrap_or_else(|| panic!("method {:#x} not in the fixture", mthd));
            u32::from_str_radix(line.split_whitespace().nth(3).unwrap(), 16).unwrap()
        };
        let m = edid_modes(&asus())[0];
        let or = want(HEAD_SET_CONTROL_OUTPUT_RESOURCE);
        for (mthd, v) in m.methods(0, or) {
            assert_eq!(v, want(mthd), "method {:#x}", mthd);
        }
        // Head 1 (the HP in the same push) is the same mode, 0x400 on.
        let hp = edid_modes(&Edid::parse(HP).unwrap())[0];
        for (mthd, v) in hp.methods(1, or).iter().take(4) {
            assert_eq!(*v, want(*mthd), "method {:#x}", mthd);
        }
    }

    #[test]
    fn methods_set_the_polarities_and_keep_the_rest() {
        let m = edid_modes(&asus())[3];
        let ms = m.methods(0, 0xfc00_0040);
        assert_eq!(ms[8], (0x2004, 0xfc00_0048), "-V: bit 3");
        assert_eq!(ms[0], (0x2064, (1125 << 16) | 2080));
        assert_eq!(ms[6], (0x200c, 420_780_000));
        let flipped = Mode { nhsync: true, nvsync: false, ..m };
        assert_eq!(flipped.methods(2, 0xfc00_004c)[8], (0x2004 + 0x800, 0xfc00_0044));
    }

    /// `Mode::timing` = the ARM state the GOP leaves for 1080p60 (the
    /// trace's supervisor fixtures read it back as `HeadTiming`).
    #[test]
    fn timing_is_what_the_head_reads_back() {
        let t = edid_modes(&asus())[0].timing(4);
        assert_eq!((t.htotal, t.vtotal, t.hsynce, t.vsynce), (2200, 1125, 43, 4));
        assert_eq!((t.hblanke, t.vblanke, t.hblanks, t.vblanks), (191, 40, 2111, 1120));
        assert_eq!(t.hz, 148_500_000);
        assert_eq!(t.refresh_mhz(), 60_000);
    }

    #[test]
    fn from_head_inverts_timing() {
        for m in edid_modes(&asus()).into_iter().chain([cvt_rb2(1920, 1080, 120).unwrap()]) {
            let or = 0xfc00_0040 | if m.nvsync { 8 } else { 0 } | if m.nhsync { 4 } else { 0 };
            assert_eq!(Mode::from_head(&m.timing(4), or), Mode { source: Source::Gop, ..m });
        }
    }

    #[test]
    fn select_prefers_the_edid_then_cvt_in_range() {
        let e = asus();
        assert_eq!(select(&e, 1920, 1080, 60).unwrap().source, Source::Edid(0));
        assert_eq!(select(&e, 1920, 1080, 144).unwrap().source, Source::Edid(1));
        let m180 = select(&e, 1920, 1080, 180).unwrap();
        assert_eq!((m180.source, m180.clock_khz), (Source::Edid(3), 420_780));
        let m120 = select(&e, 1920, 1080, 120).unwrap();
        assert_eq!((m120.source, m120.clock_khz), (Source::Cvt, 274_560));
        assert_eq!(select(&e, 1920, 1080, 47), Err(ModeError::OutOfRange));
        assert_eq!(select(&e, 1920, 1080, 181), Err(ModeError::OutOfRange));
        // 2560x1440@144 is inside 48-180 Hz but needs 586 MHz > 430.
        assert_eq!(select(&e, 2560, 1440, 144), Err(ModeError::OutOfRange));
        assert_eq!(select(&e, 1280, 720, 100).unwrap().source, Source::Cvt);
    }

    /// 1080p180 fits the VPLL and a 4x HBR2 link, not the GOP's 2x HBR
    /// (what `/dev/dispctl mode` checks before touching anything).
    #[test]
    fn the_180_hz_modes_fit_vpll_and_4x_hbr2() {
        use crate::pll;
        use crate::supervisor::{dp_config, DpLink};
        let hbr2x4 = DpLink { bw: 0x14, nr: 4, ef: true, mst: false };
        for m in [select(&asus(), 1920, 1080, 180).unwrap(), cvt_rb2(1920, 1080, 180).unwrap()] {
            let c = pll::calc(&pll::tests::vpll(), m.clock_khz).unwrap();
            assert_eq!(c.p, 3, "{:?}", m);
            let hz = c.hz(27_000) as i64;
            assert!((hz - m.clock_khz as i64 * 1000).abs() < 2_000, "{} Hz for {} kHz", hz, m.clock_khz);
            let dp = dp_config(&m.timing(4), &hbr2x4).unwrap();
            assert!(dp.watermark > 6 && dp.watermark < 0x3f, "{:?}", dp);
            // 4 lanes x 5.4 Gb/s x 8/10 / 24 bpp = 720 MHz; 2x HBR = 180.
            assert!(m.clock_khz <= 4 * 0x14 * 27_000 * 8 / 24);
            assert!(m.clock_khz > 2 * 0x0a * 27_000 * 8 / 24);
        }
    }

    #[test]
    fn requests_parse() {
        assert_eq!(parse_request("1920x1080@180"), Ok((1920, 1080, 180)));
        assert_eq!(parse_request("1920x1080"), Err(ModeError::Syntax));
        assert_eq!(parse_request("1920x@60"), Err(ModeError::Syntax));
        assert_eq!(parse_request("0x1080@60"), Err(ModeError::Syntax));
        assert_eq!(parse_request("99999x1080@60"), Err(ModeError::Syntax));
    }
}
